// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6-6KR2lgJ67bmbQKmSt1EXP6RB7KoxE',
    appId: '1:302492772767:android:41175e1564d87e507c35aa',
    messagingSenderId: '302492772767',
    projectId: 'insurance-reminder-6899c',
    storageBucket: 'insurance-reminder-6899c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsmhLiB5tUH8BiqRI_iuVB1n_aCpEgnw',
    appId: '1:302492772767:ios:c270474564c4be097c35aa',
    messagingSenderId: '302492772767',
    projectId: 'insurance-reminder-6899c',
    storageBucket: 'insurance-reminder-6899c.firebasestorage.app',
    androidClientId: '302492772767-3vo5u7sdqs71q6odt984ptrkqj1np3j9.apps.googleusercontent.com',
    iosClientId: '302492772767-sia4ikp13r3uukts9713q1q76jbr2hcs.apps.googleusercontent.com',
    iosBundleId: 'com.devendiran.ninaivu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvstfkxTOhfLuoXd6mCOt9t2KXPVEKxHo',
    appId: '1:302492772767:web:23f5e7d83b462bc47c35aa',
    messagingSenderId: '302492772767',
    projectId: 'insurance-reminder-6899c',
    authDomain: 'insurance-reminder-6899c.firebaseapp.com',
    storageBucket: 'insurance-reminder-6899c.firebasestorage.app',
    measurementId: 'G-BH5QQSZ673',
  );

}