// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6-6KR2lgJ67bmbQKmSt1EXP6RB7KoxE',
    appId: '1:302492772767:android:e0fca0496402659a7c35aa',
    messagingSenderId: '302492772767',
    projectId: 'insurance-reminder-6899c',
    storageBucket: 'insurance-reminder-6899c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsmhLiB5tUH8BiqRI_iuVB1n_aCpEgnw',
    appId: '1:302492772767:ios:49e786b43836cca97c35aa',
    messagingSenderId: '302492772767',
    projectId: 'insurance-reminder-6899c',
    storageBucket: 'insurance-reminder-6899c.firebasestorage.app',
    androidClientId:
        '302492772767-3vo5u7sdqs71q6odt984ptrkqj1np3j9.apps.googleusercontent.com',
    iosClientId:
        '302492772767-d72pnkslnf3fs8547deh5fv0u7sd86gb.apps.googleusercontent.com',
    iosBundleId: 'com.devendiran.insuranceReminders',
  );
}
